// src/components/PomodoroTimer.vue
<template>
  <div class="max-w-xs mx-auto p-4 bg-white dark:bg-gray-800 rounded shadow">
    <h2 class="text-xl font-bold mb-2 text-center">Pomodoro Timer</h2>
    <div class="flex flex-col items-center">
      <div class="text-4xl font-mono mb-2">{{ minutes }}:{{ seconds }}</div>
      <div class="mb-2">
        <button v-for="mode in modes" :key="mode" @click="setMode(mode)" :class="['px-2 py-1 mx-1 rounded', mode === currentMode ? 'bg-blue-500 text-white' : 'bg-gray-200 dark:bg-gray-700']">
          {{ modeLabels[mode] }}
        </button>
      </div>
      <div class="flex gap-2 mb-2">
        <button @click="toggleTimer" class="px-3 py-1 bg-green-500 text-white rounded">{{ running ? 'Pause' : 'Start' }}</button>
        <button @click="resetTimer" class="px-3 py-1 bg-gray-400 text-white rounded">Reset</button>
      </div>
      <div class="text-sm text-gray-500">Completed: {{ completedSessions }}</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';

const modes = ['work', 'short', 'long'] as const;
const modeLabels = { work: 'Work', short: 'Short Break', long: 'Long Break' };
const durations = { work: 25 * 60, short: 5 * 60, long: 15 * 60 };

const currentMode = ref<typeof modes[number]>('work');
const timeLeft = ref(durations[currentMode.value]);
const running = ref(false);
const completedSessions = ref(0);
let timer: number | null = null;

const minutes = computed(() => String(Math.floor(timeLeft.value / 60)).padStart(2, '0'));
const seconds = computed(() => String(timeLeft.value % 60).padStart(2, '0'));

function setMode(mode: typeof modes[number]) {
  currentMode.value = mode;
  resetTimer();
}

function toggleTimer() {
  running.value = !running.value;
}

function resetTimer() {
  running.value = false;
  timeLeft.value = durations[currentMode.value];
}

watch(running, (val) => {
  if (val) {
    timer = setInterval(() => {
      if (timeLeft.value > 0) {
        timeLeft.value--;
      } else {
        running.value = false;
        if (currentMode.value === 'work') completedSessions.value++;
        resetTimer();
      }
    }, 1000);
  } else if (timer) {
    clearInterval(timer);
    timer = null;
  }
});

watch(currentMode, () => {
  timeLeft.value = durations[currentMode.value];
});
</script>

// src/pages/DayView/PomodoroTimer.jsx
import { useState, useRef } from "react";
import { useTranslation } from "react-i18next";

export default function PomodoroTimer() {
  const { t } = useTranslation();
  const [seconds, setSeconds] = useState(25 * 60);
  const [running, setRunning] = useState(false);
  const intervalRef = useRef(null);

  function start() {
    if (!running) {
      setRunning(true);
      intervalRef.current = setInterval(() => {
        setSeconds((s) => (s > 0 ? s - 1 : 0));
      }, 1000);
    }
  }
  function pause() {
    setRunning(false);
    clearInterval(intervalRef.current);
  }
  function reset() {
    setRunning(false);
    clearInterval(intervalRef.current);
    setSeconds(25 * 60);
  }

  // Cleanup
  React.useEffect(() => {
    if (seconds === 0) {
      pause();
    }
    return () => clearInterval(intervalRef.current);
  }, [seconds]);

  const min = String(Math.floor(seconds / 60)).padStart(2, "0");
  const sec = String(seconds % 60).padStart(2, "0");

  return (
    <div className="rounded-2xl bg-gradient-to-br from-emerald-100 to-blue-100 dark:from-zinc-800 dark:to-zinc-900 border border-slate-200 dark:border-slate-800 shadow p-4 flex flex-col items-center">
      <span className="font-bold text-lg text-emerald-700 dark:text-emerald-400 mb-2">{t("pomodoro", "مؤقت بومودورو")}</span>
      <span className="text-3xl font-extrabold text-blue-700 dark:text-sky-400 tabular-nums">{min}:{sec}</span>
      <div className="mt-3 flex gap-2">
        <button onClick={start} disabled={running} className="px-4 py-1 rounded-full bg-blue-600 text-white font-semibold hover:bg-blue-700 transition disabled:opacity-50">{t("start", "ابدأ")}</button>
        <button onClick={pause} disabled={!running} className="px-4 py-1 rounded-full bg-amber-500 text-white font-semibold hover:bg-amber-600 transition disabled:opacity-50">{t("pause", "إيقاف")}</button>
        <button onClick={reset} className="px-4 py-1 rounded-full bg-slate-200 dark:bg-zinc-700 text-slate-700 dark:text-slate-200 font-semibold hover:bg-slate-300 dark:hover:bg-zinc-600 transition">{t("reset", "إعادة")}</button>
      </div>
    </div>
  );
}
