// src/components/week/PomodoroTimer.vue
<template>
  <div class="flex flex-col items-center gap-4">
    <div class="flex gap-2 mb-2">
      <button v-for="mode in modes" :key="mode.key" @click="setMode(mode.key)"
        :class="[modeKey === mode.key ? 'bg-cyan-500 text-white' : 'bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300', 'px-4 py-1 rounded-full font-bold transition']">
        {{ $t(`pomodoro.${mode.key}`) }}
      </button>
    </div>
    <div class="text-5xl font-mono font-bold text-cyan-600 dark:text-cyan-400">
      {{ minutes }}:{{ seconds < 10 ? '0' + seconds : seconds }}
    </div>
    <div class="flex gap-3 mt-2">
      <button @click="toggle" class="px-4 py-2 rounded-lg font-bold bg-gradient-to-r from-cyan-400 to-purple-500 text-white shadow hover:scale-105 transition">
        <span v-if="!running">{{ $t('pomodoro.start') }}</span>
        <span v-else>{{ $t('pomodoro.pause') }}</span>
      </button>
      <button @click="reset" class="px-4 py-2 rounded-lg font-bold bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-200 shadow hover:bg-gray-300 dark:hover:bg-gray-600 transition">
        {{ $t('pomodoro.reset') }}
      </button>
    </div>
    <div class="text-xs text-gray-500 mt-2">{{ $t('pomodoro.sessions') }}: {{ sessions }}</div>
  </div>
</template>
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useI18n } from 'vue-i18n'
const { t } = useI18n()
const modes = [
  { key: 'work', duration: 25 },
  { key: 'shortBreak', duration: 5 },
  { key: 'longBreak', duration: 15 }
]
const modeKey = ref('work')
const duration = ref(25 * 60)
const timer = ref<number | null>(null)
const running = ref(false)
const timeLeft = ref(duration.value)
const sessions = ref(0)
const minutes = computed(() => Math.floor(timeLeft.value / 60))
const seconds = computed(() => timeLeft.value % 60)
function setMode(key: string) {
  modeKey.value = key
  const mode = modes.find(m => m.key === key)
  if (mode) {
    duration.value = mode.duration * 60
    timeLeft.value = duration.value
    running.value = false
    clearTimer()
  }
}
function tick() {
  if (timeLeft.value > 0) {
    timeLeft.value--
  } else {
    running.value = false
    clearTimer()
    sessions.value++
  }
}
function toggle() {
  running.value = !running.value
  if (running.value) {
    timer.value = setInterval(tick, 1000) as unknown as number
  } else {
    clearTimer()
  }
}
function reset() {
  timeLeft.value = duration.value
  running.value = false
  clearTimer()
}
function clearTimer() {
  if (timer.value) {
    clearInterval(timer.value)
    timer.value = null
  }
}
watch(modeKey, () => reset())
</script>

// src/pages/DayView/PomodoroTimer.jsx
import { useState, useRef } from "react";
import { useTranslation } from "react-i18next";

export default function PomodoroTimer() {
  const { t } = useTranslation();
  const [seconds, setSeconds] = useState(25 * 60);
  const [running, setRunning] = useState(false);
  const intervalRef = useRef(null);

  function start() {
    if (!running) {
      setRunning(true);
      intervalRef.current = setInterval(() => {
        setSeconds((s) => (s > 0 ? s - 1 : 0));
      }, 1000);
    }
  }
  function pause() {
    setRunning(false);
    clearInterval(intervalRef.current);
  }
  function reset() {
    setRunning(false);
    clearInterval(intervalRef.current);
    setSeconds(25 * 60);
  }

  // Cleanup
  React.useEffect(() => {
    if (seconds === 0) {
      pause();
    }
    return () => clearInterval(intervalRef.current);
  }, [seconds]);

  const min = String(Math.floor(seconds / 60)).padStart(2, "0");
  const sec = String(seconds % 60).padStart(2, "0");

  return (
    <div className="rounded-2xl bg-gradient-to-br from-emerald-100 to-blue-100 dark:from-zinc-800 dark:to-zinc-900 border border-slate-200 dark:border-slate-800 shadow p-4 flex flex-col items-center">
      <span className="font-bold text-lg text-emerald-700 dark:text-emerald-400 mb-2">{t("pomodoro", "مؤقت بومودورو")}</span>
      <span className="text-3xl font-extrabold text-blue-700 dark:text-sky-400 tabular-nums">{min}:{sec}</span>
      <div className="mt-3 flex gap-2">
        <button onClick={start} disabled={running} className="px-4 py-1 rounded-full bg-blue-600 text-white font-semibold hover:bg-blue-700 transition disabled:opacity-50">{t("start", "ابدأ")}</button>
        <button onClick={pause} disabled={!running} className="px-4 py-1 rounded-full bg-amber-500 text-white font-semibold hover:bg-amber-600 transition disabled:opacity-50">{t("pause", "إيقاف")}</button>
        <button onClick={reset} className="px-4 py-1 rounded-full bg-slate-200 dark:bg-zinc-700 text-slate-700 dark:text-slate-200 font-semibold hover:bg-slate-300 dark:hover:bg-zinc-600 transition">{t("reset", "إعادة")}</button>
      </div>
    </div>
  );
}
